<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [7]:
%%sql

SELECT
  DATE_TRUNC('month', orderdate)::date AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM sales
GROUP BY
  order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_unique_customers
0    2015-01-01    384092.66                     200
1    2015-02-01    706374.12                     291
2    2015-03-01    332961.59                     139
3    2015-04-01    160767.00                      78
4    2015-05-01    548632.63                     236
..          ...          ...                     ...
107  2023-12-01   2928550.93                    1484
108  2024-01-01   2677498.55                    1340
109  2024-02-01   3542322.55                    1718
110  2024-03-01   1692854.89                     877
111  2024-04-01    483851.39                     246

[112 rows x 3 columns]

In [8]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS total_unique_customers
FROM sales
GROUP BY
  order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_month  net_revenue  total_unique_customers
0       2015-01    384092.66                     200
1       2015-02    706374.12                     291
2       2015-03    332961.59                     139
3       2015-04    160767.00                      78
4       2015-05    548632.63                     236
..          ...          ...                     ...
107     2023-12   2928550.93                    1484
108     2024-01   2677498.55                    1340
109     2024-02   3542322.55                    1718
110     2024-03   1692854.89                     877
111     2024-04    483851.39                     246

[112 rows x 3 columns]

In [11]:
%%sql

SELECT
    orderdate,
    DATE_PART('year', orderdate) AS order_year,
    DATE_PART('month', orderdate) AS order_month,
    DATE_PART('day', orderdate) AS order_day
FROM
    sales
ORDER BY RANDOM()
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  order_year  order_month  order_day
0  2024-01-30     2024.00         1.00      30.00
1  2023-03-16     2023.00         3.00      16.00
2  2021-03-13     2021.00         3.00      13.00
3  2018-01-01     2018.00         1.00       1.00
4  2024-01-13     2024.00         1.00      13.00
5  2018-02-02     2018.00         2.00       2.00
6  2016-01-19     2016.00         1.00      19.00
7  2024-01-29     2024.00         1.00      29.00
8  2022-12-29     2022.00        12.00      29.00
9  2019-08-22     2019.00         8.00      22.00

In [13]:
%%sql

SELECT
    orderdate,
    EXTRACT(YEAR FROM orderdate) AS order_year,
    EXTRACT(MONTH FROM orderdate) AS order_month,
    EXTRACT(DAY FROM orderdate) AS order_day
FROM
    sales
ORDER BY RANDOM()
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate order_year order_month order_day
0  2019-02-28       2019           2        28
1  2022-08-06       2022           8         6
2  2022-02-09       2022           2         9
3  2023-03-16       2023           3        16
4  2024-02-17       2024           2        17
5  2018-08-18       2018           8        18
6  2022-11-21       2022          11        21
7  2021-11-29       2021          11        29
8  2019-08-20       2019           8        20
9  2023-07-22       2023           7        22

In [17]:
%%sql

SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(MONTH FROM orderdate) AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM sales
GROUP BY
  order_year,
  order_month
ORDER BY
  order_year,
  order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    order_year order_month  net_revenue
0         2015           1    384092.66
1         2015           2    706374.12
2         2015           3    332961.59
3         2015           4    160767.00
4         2015           5    548632.63
..         ...         ...          ...
107       2023          12   2928550.93
108       2024           1   2677498.55
109       2024           2   3542322.55
110       2024           3   1692854.89
111       2024           4    483851.39

[112 rows x 3 columns]

In [23]:
%%sql

SELECT
  CURRENT_DATE,
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(YEAR FROM CURRENT_DATE) AS current_year,
  EXTRACT(YEAR FROM CURRENT_DATE) -5 AS minus_five,
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales AS s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  EXTRACT(YEAR FROM s.orderdate) = EXTRACT(YEAR FROM CURRENT_DATE) -5
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2534 rows affected.

,current_date,order_year,current_year,minus_five,orderdate,categoryname,net_revenue
0,2026-03-19,2021,2026,2021,2021-01-01,Audio,1206.67
1,2026-03-19,2021,2026,2021,2021-01-01,Cameras and camcorders,2228.75
2,2026-03-19,2021,2026,2021,2021-01-01,Cell phones,10582.00
3,2026-03-19,2021,2026,2021,2021-01-01,Computers,12718.95
4,2026-03-19,2021,2026,2021,2021-01-01,Games and Toys,235.53
...,...,...,...,...,...,...,...
2529,2026-03-19,2021,2026,2021,2021-12-31,Computers,43444.94
2530,2026-03-19,2021,2026,2021,2021-12-31,Games and Toys,1779.80
2531,2026-03-19,2021,2026,2021,2021-12-31,Home Appliances,24621.59
2532,2026-03-19,2021,2026,2021,2021-12-31,"Music, Movies and Audio Books",5169.00
2533,2026-03-19,2021,2026,2021,2021-12-31,TV and Video,8696.26

In [25]:
%%sql

SELECT
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales AS s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  EXTRACT(YEAR FROM s.orderdate) = EXTRACT(YEAR FROM CURRENT_DATE) -6
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2214 rows affected.

       orderdate                   categoryname  net_revenue
0     2020-01-01                          Audio      5490.14
1     2020-01-01        Cameras and camcorders      18880.06
2     2020-01-01                    Cell phones     22593.00
3     2020-01-01                      Computers     78554.54
4     2020-01-01                 Games and Toys      1476.43
...          ...                            ...          ...
2209  2020-12-31                      Computers     16203.88
2210  2020-12-31                 Games and Toys       288.19
2211  2020-12-31                Home Appliances       251.09
2212  2020-12-31  Music, Movies and Audio Books      2699.40
2213  2020-12-31                   TV and Video      4494.98

[2214 rows x 3 columns]

In [26]:
%%sql

SELECT INTERVAL '5 centuries'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

               interval
0  182500 days, 0:00:00

In [30]:
%%sql

SELECT
  CURRENT_DATE,
  orderdate
FROM sales
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '6 years'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

118660 rows affected.

       current_date   orderdate
0        2026-03-19  2020-03-19
1        2026-03-19  2020-03-19
2        2026-03-19  2020-03-19
3        2026-03-19  2020-03-19
4        2026-03-19  2020-03-19
...             ...         ...
118655   2026-03-19  2024-04-20
118656   2026-03-19  2024-04-20
118657   2026-03-19  2024-04-20
118658   2026-03-19  2024-04-20
118659   2026-03-19  2024-04-20

[118660 rows x 2 columns]

In [33]:
%%sql

SELECT
  CURRENT_DATE,
  s.orderdate,
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue
FROM sales AS s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '6 years'
GROUP BY
  s.orderdate,
  p.categoryname
ORDER BY
  s.orderdate,
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10581 rows affected.

      current_date   orderdate                   categoryname  net_revenue
0       2026-03-19  2020-03-19                          Audio      2793.95
1       2026-03-19  2020-03-19        Cameras and camcorders       4592.67
2       2026-03-19  2020-03-19                    Cell phones      8323.75
3       2026-03-19  2020-03-19                      Computers     14223.14
4       2026-03-19  2020-03-19                 Games and Toys       376.11
...            ...         ...                            ...          ...
10576   2026-03-19  2024-04-20                      Computers     58353.68
10577   2026-03-19  2024-04-20                 Games and Toys      1744.30
10578   2026-03-19  2024-04-20                Home Appliances      1562.04
10579   2026-03-19  2024-04-20  Music, Movies and Audio Books      4949.43
10580   2026-03-19  2024-04-20                   TV and Video      9841.91

[10581 rows x 4 columns]

In [34]:
%%sql

SELECT
  orderdate,
  deliverydate
FROM
 sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

         orderdate deliverydate
0       2015-01-01   2015-01-01
1       2015-01-01   2015-01-01
2       2015-01-01   2015-01-01
3       2015-01-01   2015-01-01
4       2015-01-01   2015-01-01
...            ...          ...
199868  2024-04-20   2024-04-21
199869  2024-04-20   2024-04-21
199870  2024-04-20   2024-04-22
199871  2024-04-20   2024-04-22
199872  2024-04-20   2024-04-22

[199873 rows x 2 columns]

In [36]:
%%sql

SELECT EXTRACT(DAY FROM AGE('2024-01-14','2024-01-08')) - 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  ?column?
0        1

In [47]:
%%sql

SELECT
  DATE_PART('year', orderdate) AS order_year,
  ROUND(AVG(EXTRACT(DAYS FROM AGE(deliverydate, orderdate))), 2) AS avg_processing_time,
  CAST(SUM(quantity * netprice * exchangerate)AS INTEGER) AS net_revenue
FROM
 sales
WHERE
  orderdate >= CURRENT_DATE - INTERVAL '6 years'
GROUP BY
  order_year
ORDER BY
  order_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

   order_year avg_processing_time  net_revenue
0     2020.00                0.96      5499475
1     2021.00                1.36     21357977
2     2022.00                1.62     44864557
3     2023.00                1.75     33108566
4     2024.00                1.67      8396527