<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [11]:
%%sql

WITH monthly_revenue as (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') as month,
    SUM(quantity * netprice * exchangerate) as net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  FIRST_VALUE(net_revenue) OVER (ORDER BY month) as first_month_revenue,
  LAST_VALUE(net_revenue) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as last_month_revenue,
  NTH_VALUE(net_revenue, 3) OVER (ORDER BY month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) as third_month_revenue
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,first_month_revenue,last_month_revenue,third_month_revenue
0,2023-01,3664431.34,3664431.34,2928550.93,2244316.52
1,2023-02,4465204.57,3664431.34,2928550.93,2244316.52
2,2023-03,2244316.52,3664431.34,2928550.93,2244316.52
3,2023-04,1162796.16,3664431.34,2928550.93,2244316.52
4,2023-05,2943005.99,3664431.34,2928550.93,2244316.52
5,2023-06,2864500.03,3664431.34,2928550.93,2244316.52
6,2023-07,2337639.34,3664431.34,2928550.93,2244316.52
7,2023-08,2623919.79,3664431.34,2928550.93,2244316.52
8,2023-09,2622774.85,3664431.34,2928550.93,2244316.52
9,2023-10,2551322.61,3664431.34,2928550.93,2244316.52
10,2023-11,2700103.38,3664431.34,2928550.93,2244316.52
11,2023-12,2928550.93,3664431.34,2928550.93,2244316.52

In [15]:
%%sql

WITH monthly_revenue as (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') as month,
    SUM(quantity * netprice * exchangerate) as net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  LAG(net_revenue) OVER (ORDER BY month) as previous_month_revenue,
  LEAD(net_revenue) OVER (ORDER BY month) as next_month_revenue
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  previous_month_revenue
0   2023-01   3664431.34                     NaN
1   2023-02   4465204.57              3664431.34
2   2023-03   2244316.52              4465204.57
3   2023-04   1162796.16              2244316.52
4   2023-05   2943005.99              1162796.16
5   2023-06   2864500.03              2943005.99
6   2023-07   2337639.34              2864500.03
7   2023-08   2623919.79              2337639.34
8   2023-09   2622774.85              2623919.79
9   2023-10   2551322.61              2622774.85
10  2023-11   2700103.38              2551322.61
11  2023-12   2928550.93              2700103.38

In [18]:
%%sql

WITH monthly_revenue as (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') as month,
    SUM(quantity * netprice * exchangerate) as net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  *,
  LAG(net_revenue) OVER (ORDER BY month) as previous_month_revenue,
  100 * (net_revenue - LAG(net_revenue) OVER (ORDER BY month)) /
  LAG(net_revenue) OVER (ORDER BY month) as monthly_rev_growth
FROM monthly_revenue

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  previous_month_revenue  monthly_rev_growth
0   2023-01   3664431.34                     NaN                 NaN
1   2023-02   4465204.57              3664431.34               21.85
2   2023-03   2244316.52              4465204.57              -49.74
3   2023-04   1162796.16              2244316.52              -48.19
4   2023-05   2943005.99              1162796.16              153.10
5   2023-06   2864500.03              2943005.99               -2.67
6   2023-07   2337639.34              2864500.03              -18.39
7   2023-08   2623919.79              2337639.34               12.25
8   2023-09   2622774.85              2623919.79               -0.04
9   2023-10   2551322.61              2622774.85               -2.72
10  2023-11   2700103.38              2551322.61                5.83
11  2023-12   2928550.93              2700103.38                8.46