<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT
  p.categoryname,
  AVG(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS avg_net_revenue_2022,
  MIN(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS min_net_revenue_2022,
  MAX(CASE WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS max_net_revenue_2022,
  AVG(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS avg_net_revenue_2023,
  MIN(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS min_net_revenue_2023,
  MAX(CASE WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS max_net_revenue_2023
FROM
  sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,min_net_revenue_2022,max_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2023,max_net_revenue_2023
0,Audio,50.18,0.00,3473.36,45.06,0.00,2730.87
1,Cameras and camcorders,176.85,0.00,15008.39,147.23,0.00,13572.00
2,Cell phones,194.66,0.00,7692.37,143.89,0.00,8912.22
3,Computers,384.13,0.00,38082.66,250.55,0.00,27611.60
4,Games and Toys,15.60,0.00,5202.01,13.34,0.00,3357.30
5,Home Appliances,390.05,0.00,31654.55,349.20,0.00,32915.59
6,"Music, Movies and Audio Books",93.37,0.00,5415.19,68.11,0.00,3804.91
7,TV and Video,425.35,0.00,30259.41,322.72,0.00,27503.12

In [5]:
%%sql

SELECT
    PERCENTILE_CONT(.50) WITHIN GROUP (ORDER BY netprice) AS median_price
FROM
    sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [11]:
%%sql

SELECT
  p.categoryname AS category,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2022_median_sales
FROM
  sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  y2022_median_sales
0                          Audio              257.21
1        Cameras and camcorders               651.46
2                    Cell phones              418.60
3                      Computers              809.70
4                 Games and Toys               33.78
5                Home Appliances              791.00
6  Music, Movies and Audio Books              186.58
7                   TV and Video              730.46

In [ ]:
%%sql

SELECT
  p.categoryname AS category,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2023_median_sales
FROM
  sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

In [16]:
%%sql

SELECT
  p.categoryname AS category,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2022-01-01' AND '2022-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2022_median_sales,
  PERCENTILE_CONT(.5) WITHIN GROUP (ORDER BY (CASE
    WHEN s.orderdate BETWEEN '2023-01-01' AND '2023-12-31' THEN (s.quantity * s.netprice * s.exchangerate)
  END)) AS y2023_median_sales
FROM
  sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY
  p.categoryname
ORDER BY
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79